/**
 * Progress Log - Persistent build progress tracking
 * Writes a PROGRESS.md file in the project directory
 */

import { getBuildSettings } from './prompts'

interface BuildStep {
  id: string
  name: string
  type: string
  status: 'pending' | 'building' | 'complete' | 'failed'
  filesCreated: string[]
}

interface LogEntry {
  time: string
  event: string
  details: string
}

// In-memory log for current build session
let currentBuildLog: LogEntry[] = []
let buildStartTime: string | null = null

/**
 * Initialize a new build log
 */
export function initProgressLog(projectName: string): void {
  if (!getBuildSettings().writeProgressLog) return
  
  currentBuildLog = []
  buildStartTime = new Date().toLocaleString()
  
  addLogEntry('BUILD_START', `Starting build for ${projectName}`)
}

/**
 * Add an entry to the progress log
 */
export function addLogEntry(event: string, details: string): void {
  if (!getBuildSettings().writeProgressLog) return
  
  currentBuildLog.push({
    time: new Date().toLocaleTimeString(),
    event,
    details
  })
}

/**
 * Log step start
 */
export function logStepStart(step: BuildStep, attemptNumber: number = 1): void {
  if (!getBuildSettings().writeProgressLog) return
  
  if (attemptNumber === 1) {
    addLogEntry('STEP_START', `Beginning: ${step.name}`)
  } else {
    addLogEntry('STEP_RETRY', `Retry ${attemptNumber}: ${step.name}`)
  }
}

/**
 * Log step completion
 */
export function logStepComplete(step: BuildStep, attempts: number): void {
  if (!getBuildSettings().writeProgressLog) return
  
  const filesInfo = step.filesCreated.length > 0 
    ? ` (${step.filesCreated.length} files)` 
    : ''
  addLogEntry('STEP_COMPLETE', `${step.name} completed in ${attempts} attempt(s)${filesInfo}`)
}

/**
 * Log step failure
 */
export function logStepFailed(step: BuildStep, attempts: number, reason?: string): void {
  if (!getBuildSettings().writeProgressLog) return
  
  addLogEntry('STEP_FAILED', `${step.name} failed after ${attempts} attempts${reason ? `: ${reason}` : ''}`)
}

/**
 * Generate the PROGRESS.md content
 */
export function generateProgressMarkdown(
  projectName: string,
  steps: BuildStep[],
  totalElapsed: number
): string {
  const formatTime = (seconds: number): string => {
    const mins = Math.floor(seconds / 60)
    const secs = seconds % 60
    return `${mins}m ${secs}s`
  }
  
  const getStatusEmoji = (status: string): string => {
    switch (status) {
      case 'complete': return '✅'
      case 'failed': return '❌'
      case 'building': return '🔄'
      default: return '⏳'
    }
  }
  
  const completedSteps = steps.filter(s => s.status === 'complete').length
  const failedSteps = steps.filter(s => s.status === 'failed').length
  const pendingSteps = steps.filter(s => s.status === 'pending').length
  
  let status = 'In Progress'
  if (completedSteps === steps.length) status = 'Complete ✅'
  else if (failedSteps > 0) status = 'Stopped (errors)'
  
  let md = `# Jett Build Progress

## Project: ${projectName}
**Started:** ${buildStartTime || 'Unknown'}
**Status:** ${status}
**Duration:** ${formatTime(totalElapsed)}

## Summary
- ✅ Completed: ${completedSteps}
- ❌ Failed: ${failedSteps}
- ⏳ Pending: ${pendingSteps}

## Build Steps

`

  steps.forEach((step, index) => {
    const emoji = getStatusEmoji(step.status)
    md += `### ${emoji} Step ${index + 1}: ${step.name}
- **Type:** ${step.type}
- **Status:** ${step.status}
`
    if (step.filesCreated.length > 0) {
      md += `- **Files Created:** ${step.filesCreated.length}
`
      // Show first 5 files
      const filesToShow = step.filesCreated.slice(0, 5)
      filesToShow.forEach(f => {
        md += `  - ${f}
`
      })
      if (step.filesCreated.length > 5) {
        md += `  - ... and ${step.filesCreated.length - 5} more
`
      }
    }
    md += '\n'
  })

  if (currentBuildLog.length > 0) {
    md += `## Build Log

| Time | Event | Details |
|------|-------|---------|
`
    currentBuildLog.forEach(entry => {
      md += `| ${entry.time} | ${entry.event} | ${entry.details} |
`
    })
  }

  md += `
---
*Generated by Jett at ${new Date().toLocaleString()}*
`

  return md
}

/**
 * Write the progress log to disk
 */
export async function writeProgressLog(
  projectId: string,
  projectName: string,
  steps: BuildStep[],
  totalElapsed: number
): Promise<void> {
  if (!getBuildSettings().writeProgressLog) return
  
  const content = generateProgressMarkdown(projectName, steps, totalElapsed)
  
  try {
    // Write to .jett/PROGRESS.md in project directory
    await window.jett.writeFile(projectId, '.jett/PROGRESS.md', content)
  } catch (error) {
    console.warn('Could not write progress log:', error)
  }
}
